using System;
using System.Collections.Generic;
using UnityEngine.UIElements;

namespace Bindery
{

/// <summary>
/// Base class for data sources used with Unity UI Toolkit runtime binding.
/// Inherit from this, mark ReactiveProperty fields with [BindableProperty],
/// and the source generator handles all boilerplate.
///
/// IMPORTANT: [BindableProperty] fields must be assigned with field initializers
/// (e.g. <c>public ReactiveProperty&lt;float&gt; Speed = new(10f);</c>).
/// InitBindings() runs from this base constructor — before the derived
/// constructor body — so fields assigned inside a constructor are not yet set
/// when bindings are wired.
///
/// Intentionally has no dependency on R3 or UniRx — the reactive library is
/// only referenced in user code and in generated files where it is auto-detected.
/// </summary>
public abstract class BindableObject : INotifyBindablePropertyChanged, IDisposable
{
    public event EventHandler<BindablePropertyChangedEventArgs> propertyChanged;

    private readonly List<IDisposable> _disposables = new();
    private bool _disposed;

    protected BindableObject() => InitBindings();

    /// Generated by source generator — subscribes each ReactiveProperty to Notify.
    protected virtual void InitBindings() { }

    protected void Notify(string propertyName) =>
        propertyChanged?.Invoke(this, new BindablePropertyChangedEventArgs(propertyName));

    protected void Track(IDisposable disposable) =>
        _disposables.Add(disposable);

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    /// <summary>
    /// Override to release additional resources (e.g. commands created in the
    /// constructor). Always call <c>base.Dispose(disposing)</c>.
    /// </summary>
    protected virtual void Dispose(bool disposing)
    {
        if (!disposing) return;
        foreach (var d in _disposables) d.Dispose();
        _disposables.Clear();
    }
}

} // namespace Bindery
